# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Clonet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'

  # Pods for Clonet

  target 'ClonetUITests' do
    # Pods for testing
  end

end
